version: '3.8'

services:
  postgres_livros:
    image: postgres:15
    container_name: postgres_livros
    restart: always
    environment:
      POSTGRES_DB: livros
      POSTGRES_USER: livros_user
      POSTGRES_PASSWORD: livros_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - livros_network

  # Opcional: pgAdmin para administração
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_livros
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@livros.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres_livros
    networks:
      - livros_network

volumes:
  postgres_data:

networks:
  livros_network:
    driver: bridge

